# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Identify Follow Up Issues
on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  identify-follow-up-issues:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'NVIDIA-NeMo'  # Do not run on forked repositories.
    environment: main
    steps:
      - name: Checkout NVIDIA-NeMo/FW-CI-templates
        uses: actions/checkout@v6

      - name: Identify Follow Up Issues
        uses: ./.github/actions/identify-follow-up-issues
        with:
          github_token: ${{ secrets.PAT }}
          project_id: ${{ vars.COMMUNITY_PROJECT_ID }}
          org: ${{ vars.COMMUNITY_PROJECT_ORG }}
          openai_base_url: ${{ secrets.ISSUES_OPENAI_BASE_URL }}
          openai_api_key: ${{ secrets.ISSUES_OPENAI_API_KEY }}
          llm_model: ${{ vars.ISSUES_LLM_MODEL }}
